apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "operator.fullname" . }}-my-operator-pvc-lim
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.myOperatorPvcLim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.myOperatorPvcLim.storageClass | quote }}