apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: klc-controller-service
    namespace: system
  version: v1beta1
  versionPriority: 100